-- 1. Hands on 5
insert into country (co_code, co_name) values ('AF', 'Afghanistan');
insert into country (co_code, co_name) values ('AL', 'Albania');
insert into country (co_code, co_name) values ('DZ', 'Algeria');
insert into country (co_code, co_name) values ('AS', 'American Samoa');
insert into country (co_code, co_name) values ('AD', 'Andorra');
insert into country (co_code, co_name) values ('AO', 'Angola');
insert into country (co_code, co_name) values ('AI', 'Anguilla');
insert into country (co_code, co_name) values ('AQ', 'Antarctica');
insert into country (co_code, co_name) values ('AG', 'Antigua and Barbuda');
insert into country (co_code, co_name) values ('AR', 'Argentina');
insert into country (co_code, co_name) values ('AM', 'Armenia');
insert into country (co_code, co_name) values ('AW', 'Aruba');
insert into country (co_code, co_name) values ('AU', 'Australia');
insert into country (co_code, co_name) values ('AT', 'Austria');
insert into country (co_code, co_name) values ('AZ', 'Azerbaijan');
insert into country (co_code, co_name) values ('BS', 'Bahamas');
insert into country (co_code, co_name) values ('BH', 'Bahrain');
insert into country (co_code, co_name) values ('BD', 'Bangladesh');
insert into country (co_code, co_name) values ('BB', 'Barbados');
insert into country (co_code, co_name) values ('BY', 'Belarus');
insert into country (co_code, co_name) values ('BE', 'Belgium');
insert into country (co_code, co_name) values ('BZ', 'Belize');
insert into country (co_code, co_name) values ('BJ', 'Benin');
insert into country (co_code, co_name) values ('BM', 'Bermuda');
insert into country (co_code, co_name) values ('BT', 'Bhutan');
insert into country (co_code, co_name) values ('BO', 'Bolivia');
insert into country (co_code, co_name) values ('BQ', 'Bonaire, Sint Eustatius and Saba');
insert into country (co_code, co_name) values ('BA', 'Bosnia and Herzegovina');
insert into country (co_code, co_name) values ('BW', 'Botswana');
insert into country (co_code, co_name) values ('BV', 'Bouvet Island');
insert into country (co_code, co_name) values ('BR', 'Brazil');
insert into country (co_code, co_name) values ('IO', 'British Indian Ocean Territory');
insert into country (co_code, co_name) values ('BN', 'Brunei Darussalam');
insert into country (co_code, co_name) values ('BG', 'Bulgaria');
insert into country (co_code, co_name) values ('BF', 'Burkina Faso');
insert into country (co_code, co_name) values ('BI', 'Burundi');
insert into country (co_code, co_name) values ('KH', 'Cambodia');
insert into country (co_code, co_name) values ('CM', 'Cameroon');
insert into country (co_code, co_name) values ('CA', 'Canada');
insert into country (co_code, co_name) values ('CV', 'Cape Verde');
insert into country (co_code, co_name) values ('KY', 'Cayman Islands');
insert into country (co_code, co_name) values ('CF', 'Central African Republic');
insert into country (co_code, co_name) values ('TD', 'Chad');
insert into country (co_code, co_name) values ('CL', 'Chile');
insert into country (co_code, co_name) values ('CN', 'China');
insert into country (co_code, co_name) values ('CX', 'Christmas Island');
insert into country (co_code, co_name) values ('CC', 'Cocos Islands');
insert into country (co_code, co_name) values ('CO', 'Colombia');
insert into country (co_code, co_name) values ('KM', 'Comoros');
insert into country (co_code, co_name) values ('CG', 'Congo');
insert into country (co_code, co_name) values ('CD', 'Congo, the Democratic Republic of the');
insert into country (co_code, co_name) values ('CK', 'Cook Islands');
insert into country (co_code, co_name) values ('CR', 'Costa Rica');
insert into country (co_code, co_name) values ('HR', 'Croatia');
insert into country (co_code, co_name) values ('CU', 'Cuba');
insert into country (co_code, co_name) values ('CW', 'Curacao');
insert into country (co_code, co_name) values ('CY', 'Cyprus');
insert into country (co_code, co_name) values ('CZ', 'Czech Republic');
insert into country (co_code, co_name) values ('CI', 'Cote d''Ivoire');
insert into country (co_code, co_name) values ('DK', 'Denmark');
insert into country (co_code, co_name) values ('DJ', 'Djibouti');
insert into country (co_code, co_name) values ('DM', 'Dominica');
insert into country (co_code, co_name) values ('DO', 'Dominican Republic');
insert into country (co_code, co_name) values ('EC', 'Ecuador');
insert into country (co_code, co_name) values ('EG', 'Egypt');
insert into country (co_code, co_name) values ('SV', 'El Salvador');
insert into country (co_code, co_name) values ('GQ', 'Equatorial Guinea');
insert into country (co_code, co_name) values ('ER', 'Eritrea');
insert into country (co_code, co_name) values ('EE', 'Estonia');
insert into country (co_code, co_name) values ('ET', 'Ethiopia');
insert into country (co_code, co_name) values ('FK', 'Falkland Islands');
insert into country (co_code, co_name) values ('FO', 'Faroe Islands');
insert into country (co_code, co_name) values ('FJ', 'Fiji');
insert into country (co_code, co_name) values ('FI', 'Finland');
insert into country (co_code, co_name) values ('FR', 'France');
insert into country (co_code, co_name) values ('GF', 'French Guiana');
insert into country (co_code, co_name) values ('PF', 'French Polynesia');
insert into country (co_code, co_name) values ('TF', 'French Southern Territories');
insert into country (co_code, co_name) values ('GA', 'Gabon');
insert into country (co_code, co_name) values ('GM', 'Gambia');
insert into country (co_code, co_name) values ('GE', 'Georgia');
insert into country (co_code, co_name) values ('DE', 'Germany');
insert into country (co_code, co_name) values ('GH', 'Ghana');
insert into country (co_code, co_name) values ('GI', 'Gibraltar');
insert into country (co_code, co_name) values ('GR', 'Greece');
insert into country (co_code, co_name) values ('GL', 'Greenland');
insert into country (co_code, co_name) values ('GD', 'Grenada');
insert into country (co_code, co_name) values ('GP', 'Guadeloupe');
insert into country (co_code, co_name) values ('GU', 'Guam');
insert into country (co_code, co_name) values ('GT', 'Guatemala');
insert into country (co_code, co_name) values ('GG', 'Guernsey');
insert into country (co_code, co_name) values ('GN', 'Guinea');
insert into country (co_code, co_name) values ('GW', 'Guinea-Bissau');
insert into country (co_code, co_name) values ('GY', 'Guyana');
insert into country (co_code, co_name) values ('HT', 'Haiti');
insert into country (co_code, co_name) values ('HM', 'Heard Island and McDonald Islands');
insert into country (co_code, co_name) values ('VA', 'Holy See');
insert into country (co_code, co_name) values ('HN', 'Honduras');
insert into country (co_code, co_name) values ('HK', 'Hong Kong');
insert into country (co_code, co_name) values ('HU', 'Hungary');
insert into country (co_code, co_name) values ('IS', 'Iceland');
insert into country (co_code, co_name) values ('IN', 'India');
insert into country (co_code, co_name) values ('ID', 'Indonesia');
insert into country (co_code, co_name) values ('IR', 'Iran');
insert into country (co_code, co_name) values ('IQ', 'Iraq');
insert into country (co_code, co_name) values ('IE', 'Ireland');
insert into country (co_code, co_name) values ('IM', 'Isle of Man');
insert into country (co_code, co_name) values ('IL', 'Israel');
insert into country (co_code, co_name) values ('IT', 'Italy');
insert into country (co_code, co_name) values ('JM', 'Jamaica');
insert into country (co_code, co_name) values ('JP', 'Japan');
insert into country (co_code, co_name) values ('JE', 'Jersey');
insert into country (co_code, co_name) values ('JO', 'Jordan');
insert into country (co_code, co_name) values ('KZ', 'Kazakhstan');
insert into country (co_code, co_name) values ('KE', 'Kenya');
insert into country (co_code, co_name) values ('KI', 'Kiribati');
insert into country (co_code, co_name) values ('KP', 'North Korea');
insert into country (co_code, co_name) values ('KR', 'South Korea');
insert into country (co_code, co_name) values ('KW', 'Kuwait');
insert into country (co_code, co_name) values ('KG', 'Kyrgyzstan');
insert into country (co_code, co_name) values ('LA', 'Laos');
insert into country (co_code, co_name) values ('LV', 'Latvia');
insert into country (co_code, co_name) values ('LB', 'Lebanon');
insert into country (co_code, co_name) values ('LS', 'Lesotho');
insert into country (co_code, co_name) values ('LR', 'Liberia');
insert into country (co_code, co_name) values ('LY', 'Libya');
insert into country (co_code, co_name) values ('LI', 'Liechtenstein');
insert into country (co_code, co_name) values ('LT', 'Lithuania');
insert into country (co_code, co_name) values ('LU', 'Luxembourg');
insert into country (co_code, co_name) values ('MO', 'Macao');
insert into country (co_code, co_name) values ('MK', 'Macedonia');
insert into country (co_code, co_name) values ('MG', 'Madagascar');
insert into country (co_code, co_name) values ('MW', 'Malawi');
insert into country (co_code, co_name) values ('MY', 'Malaysia');
insert into country (co_code, co_name) values ('MV', 'Maldives');
insert into country (co_code, co_name) values ('ML', 'Mali');
insert into country (co_code, co_name) values ('MT', 'Malta');
insert into country (co_code, co_name) values ('MH', 'Marshall Islands');
insert into country (co_code, co_name) values ('MQ', 'Martinique');
insert into country (co_code, co_name) values ('MR', 'Mauritania');
insert into country (co_code, co_name) values ('MU', 'Mauritius');
insert into country (co_code, co_name) values ('YT', 'Mayotte');
insert into country (co_code, co_name) values ('MX', 'Mexico');
insert into country (co_code, co_name) values ('FM', 'Micronesia');
insert into country (co_code, co_name) values ('MD', 'Moldova');
insert into country (co_code, co_name) values ('MC', 'Monaco');
insert into country (co_code, co_name) values ('MN', 'Mongolia');
insert into country (co_code, co_name) values ('ME', 'Montenegro');
insert into country (co_code, co_name) values ('MS', 'Montserrat');
insert into country (co_code, co_name) values ('MA', 'Morocco');
insert into country (co_code, co_name) values ('MZ', 'Mozambique');
insert into country (co_code, co_name) values ('MM', 'Myanmar');
insert into country (co_code, co_name) values ('NA', 'Namibia');
insert into country (co_code, co_name) values ('NR', 'Nauru');
insert into country (co_code, co_name) values ('NP', 'Nepal');
insert into country (co_code, co_name) values ('NL', 'Netherlands');
insert into country (co_code, co_name) values ('NC', 'New Caledonia');
insert into country (co_code, co_name) values ('NZ', 'New Zealand');
insert into country (co_code, co_name) values ('NI', 'Nicaragua');
insert into country (co_code, co_name) values ('NE', 'Niger');
insert into country (co_code, co_name) values ('NG', 'Nigeria');
insert into country (co_code, co_name) values ('NU', 'Niue');
insert into country (co_code, co_name) values ('NF', 'Norfolk Island');
insert into country (co_code, co_name) values ('MP', 'Northern Mariana Islands');
insert into country (co_code, co_name) values ('NO', 'Norway');
insert into country (co_code, co_name) values ('OM', 'Oman');
insert into country (co_code, co_name) values ('PK', 'Pakistan');
insert into country (co_code, co_name) values ('PW', 'Palau');
insert into country (co_code, co_name) values ('PS', 'Palestine');
insert into country (co_code, co_name) values ('PA', 'Panama');
insert into country (co_code, co_name) values ('PG', 'Papua New Guinea');
insert into country (co_code, co_name) values ('PY', 'Paraguay');
insert into country (co_code, co_name) values ('PE', 'Peru');
insert into country (co_code, co_name) values ('PH', 'Philippines');
insert into country (co_code, co_name) values ('PN', 'Pitcairn');
insert into country (co_code, co_name) values ('PL', 'Poland');
insert into country (co_code, co_name) values ('PT', 'Portugal');
insert into country (co_code, co_name) values ('PR', 'Puerto Rico');
insert into country (co_code, co_name) values ('QA', 'Qatar');
insert into country (co_code, co_name) values ('RO', 'Romania');
insert into country (co_code, co_name) values ('RU', 'Russian Federation');
insert into country (co_code, co_name) values ('RW', 'Rwanda');
insert into country (co_code, co_name) values ('RE', 'Reunion');
insert into country (co_code, co_name) values ('BL', 'Saint Barthelemy');
insert into country (co_code, co_name) values ('SH', 'Saint Helena');
insert into country (co_code, co_name) values ('KN', 'Saint Kitts and Nevis');
insert into country (co_code, co_name) values ('LC', 'Saint Lucia');
insert into country (co_code, co_name) values ('MF', 'Saint Martin');
insert into country (co_code, co_name) values ('PM', 'Saint Pierre and Miquelon');
insert into country (co_code, co_name) values ('VC', 'Saint Vincent and the Grenadines');
insert into country (co_code, co_name) values ('WS', 'Samoa');
insert into country (co_code, co_name) values ('SM', 'San Marino');
insert into country (co_code, co_name) values ('ST', 'Sao Tome and Principe');
insert into country (co_code, co_name) values ('SA', 'Saudi Arabia');
insert into country (co_code, co_name) values ('SN', 'Senegal');
insert into country (co_code, co_name) values ('RS', 'Serbia');
insert into country (co_code, co_name) values ('SC', 'Seychelles');
insert into country (co_code, co_name) values ('SL', 'Sierra Leone');
insert into country (co_code, co_name) values ('SG', 'Singapore');
insert into country (co_code, co_name) values ('SX', 'Sint Maarten');
insert into country (co_code, co_name) values ('SK', 'Slovakia');
insert into country (co_code, co_name) values ('SI', 'Slovenia');
insert into country (co_code, co_name) values ('SB', 'Solomon Islands');
insert into country (co_code, co_name) values ('SO', 'Somalia');
insert into country (co_code, co_name) values ('ZA', 'South Africa');
insert into country (co_code, co_name) values ('GS', 'South Georgia and the South Sandwich Islands');
insert into country (co_code, co_name) values ('SS', 'South Sudan');
insert into country (co_code, co_name) values ('ES', 'Spain');
insert into country (co_code, co_name) values ('LK', 'Sri Lanka');
insert into country (co_code, co_name) values ('SD', 'Sudan');
insert into country (co_code, co_name) values ('SR', 'Suriname');
insert into country (co_code, co_name) values ('SJ', 'Svalbard and Jan Mayen');
insert into country (co_code, co_name) values ('SZ', 'Swaziland');
insert into country (co_code, co_name) values ('SE', 'Sweden');
insert into country (co_code, co_name) values ('CH', 'Switzerland');
insert into country (co_code, co_name) values ('SY', 'Syrian Arab Republic');
insert into country (co_code, co_name) values ('TW', 'Taiwan');
insert into country (co_code, co_name) values ('TJ', 'Tajikistan');
insert into country (co_code, co_name) values ('TZ', 'Tanzania');
insert into country (co_code, co_name) values ('TH', 'Thailand');
insert into country (co_code, co_name) values ('TL', 'Timor-Leste');
insert into country (co_code, co_name) values ('TG', 'Togo');
insert into country (co_code, co_name) values ('TK', 'Tokelau');
insert into country (co_code, co_name) values ('TO', 'Tonga');
insert into country (co_code, co_name) values ('TT', 'Trinidad and Tobago');
insert into country (co_code, co_name) values ('TN', 'Tunisia');
insert into country (co_code, co_name) values ('TR', 'Turkey');
insert into country (co_code, co_name) values ('TM', 'Turkmenistan');
insert into country (co_code, co_name) values ('TC', 'Turks and Caicos Islands');
insert into country (co_code, co_name) values ('TV', 'Tuvalu');
insert into country (co_code, co_name) values ('UG', 'Uganda');
insert into country (co_code, co_name) values ('UA', 'Ukraine');
insert into country (co_code, co_name) values ('AE', 'United Arab Emirates');
insert into country (co_code, co_name) values ('GB', 'United Kingdom');
insert into country (co_code, co_name) values ('US', 'United States');
insert into country (co_code, co_name) values ('UM', 'United States Minor Outlying Islands');
insert into country (co_code, co_name) values ('UY', 'Uruguay');
insert into country (co_code, co_name) values ('UZ', 'Uzbekistan');
insert into country (co_code, co_name) values ('VU', 'Vanuatu');
insert into country (co_code, co_name) values ('VE', 'Venezuela');
insert into country (co_code, co_name) values ('VN', 'Viet Nam');
insert into country (co_code, co_name) values ('VG', 'Virgin Islands, British');
insert into country (co_code, co_name) values ('VI', 'Virgin Islands, U.S.');
insert into country (co_code, co_name) values ('WF', 'Wallis and Futuna');
insert into country (co_code, co_name) values ('EH', 'Western Sahara');
insert into country (co_code, co_name) values ('YE', 'Yemen');
insert into country (co_code, co_name) values ('ZM', 'Zambia');
insert into country (co_code, co_name) values ('ZW', 'Zimbabwe');

-- 2. Hands on 2
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-03', 185.84, 182.04, 12614226);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-04', 180.51, 177.63, 9719583);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-05', 178.69, 181.83, 9458591);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-06', 182.37, 178.62, 9571945);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-09', 176.93, 176.97, 8445199);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-10', 177.34, 179.07, 17142600);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-11', 178.59, 178.18, 12667265);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-12', 180.04, 176.09, 10678638);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-13', 177.28, 176.0, 10608513);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-16', 174.29, 176.4, 9714803);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-17', 173.96, 170.73, 13770619);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-18', 171.35, 173.81, 15707870);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-19', 174.03, 177.81, 14350753);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-20', 175.28, 173.63, 18546825);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-23', 174.34, 177.23, 17686361);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-24', 175.38, 171.94, 11823498);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-25', 173.58, 177.46, 11905582);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-26', 179.66, 178.7, 15606962);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-09-27', 179.51, 178.43, 14210606);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-22', 1236.67, 1253.76, 2390113);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-23', 1256.64, 1270.59, 1778736);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-24', 1270.59, 1260.05, 2019786);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-25', 1270.3, 1267.34, 3618057);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-26', 1273.38, 1277.42, 1199483);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-04-29', 1280.51, 1296.2, 3454880);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-10-17', 1251.4, 1252.8, 3563291);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-05-01', 1122.25, 1126.83, 1242679);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-05-02', 1160.09, 1155.49, 1360566);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('GOOGL', '2019-05-03', 1189.0, 1195.86, 1017310);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2019-01-31', 165.6, 166.69, 77233600);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2018-10-31', 155.0, 151.79, 60101300);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('FB', '2018-12-19', 141.21, 133.24, 57404900);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2018-12-24', 242.0, 233.88, 9547600);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2018-12-21', 263.83, 246.39, 21397600);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2018-12-26', 233.92, 253.67, 14402700);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2019-06-10', 349.16, 339.8, 6646211);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2019-06-11', 356.05, 347.37, 8757851);
insert into stock (st_code, st_date, st_open, st_close, st_volume) values ('NFLX', '2019-06-12', 375.05, 371.34, 8187855);

-- 2. Hands on 3
insert into department (dp_name) values ('Engineering');
insert into department (dp_name) values ('Human Resources');
insert into department (dp_name) values ('Finance');

insert into skill (sk_name) values ('Java');
insert into skill (sk_name) values ('SQL');
insert into skill (sk_name) values ('Communication');
insert into skill (sk_name) values ('Python');

insert into employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) values ('Ravi Kumar', 75000, true, '1995-04-12', 1);
insert into employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) values ('Sneha Reddy', 68000, true, '1997-08-23', 1);
insert into employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) values ('Arjun Rao', 55000, false, '1999-01-05', 2);
insert into employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) values ('Priya Sharma', 82000, true, '1993-11-30', 3);

-- 2. Hands on 6
insert into employee_skill (es_em_id, es_sk_id) values (1, 1);
insert into employee_skill (es_em_id, es_sk_id) values (1, 2);
insert into employee_skill (es_em_id, es_sk_id) values (2, 3);