# Exercise: Creating Microservices for account and loan
server.port=8080
# Exercise: Register Account REST API to eureka discovery
spring.application.name=account-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
